name: Windows Release

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  release-windows:
    name: Build and release for Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-glfw
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and compile
        run: |
          cd src && make
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: json_x_glfw_opengl3-windows-amd64_${{ env.sha_short }}
          path: src\json_x_glfw_opengl3-windows-amd64.exe

  release-macos:
    name: Build and release for MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Glfw3
        run: |
          brew install glfw
      - name: Build and compile
        run: |
          cd src && make
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: json_x_glfw_opengl3-macos-amd64_${{ env.sha_short }}
          path: src\json_x_glfw_opengl3-macos-amd64
