name: Windows Release

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  release:
    name: Build and release for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and compile
        run: >
          cd "C:/Program Files (x86)/glfw3" && dir
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: json_x_glfw_opengl3-windows-amd64.exe
